version: "3.8"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - ai_network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - ai_network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - ai_network
    volumes:
      - ./shared_data:/shared_data


  frontend:
    build: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
    networks:
      - ai_network
    restart: unless-stopped

  scraper:
    build: ./scraper
    volumes:
      - ./shared_data:/shared_data
    environment:
      - OUTPUT_DIR=/shared_data
    networks:
      - ai_network
    depends_on:
      - elasticsearch


volumes:
  esdata:

networks:
  ai_network:
    driver: bridge
